# Generated by Django 4.2.1 on 2023-06-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(
                        choices=[
                            ("Desk", "Desk"),
                            ("Laptop", "Laptop"),
                            ("Phone", "Phone"),
                            ("Tablet", "Tablet"),
                            ("Printer", "Printer"),
                        ],
                        max_length=100,
                    ),
                ),
                ("asset_serial", models.CharField(max_length=100)),
                ("asset_manufacturer", models.CharField(max_length=100)),
                ("date_purchased", models.DateTimeField()),
                ("asset_assigned", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_name", models.CharField(max_length=100)),
                (
                    "employee_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("employee_contact", models.CharField(max_length=100)),
                ("employee_email", models.EmailField(max_length=100)),
                ("employee_address", models.TextField()),
                (
                    "employee_department",
                    models.CharField(
                        choices=[
                            ("Accounts", "Accounts"),
                            ("IT", "IT"),
                            ("Planning", "Planning"),
                            ("Marketing", "Marketing"),
                            ("Corporate", "Corporate"),
                            ("HR", "HR"),
                            ("Security", "Security"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "employee_designation",
                    models.CharField(
                        choices=[
                            ("Jr. Executive", "Jr. Executive"),
                            ("Sr. Executive", "Sr. Executive"),
                            ("Asst. Manager", "Assistant Manager"),
                            ("Manager", "Manager"),
                            ("Head", "Head"),
                            ("GM", "General Manager"),
                            ("CEO", "Chief Executive Officer"),
                            ("CFO", "Cheif Financial Officer"),
                            ("CTO", "Cheif Technical Officer"),
                            ("MD", "Managing Director"),
                            ("ED", "Executive Director"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_assigned",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "asset_condition_when_assigned",
                    models.CharField(
                        choices=[
                            ("Fresh", "Fresh"),
                            ("Used", "Used"),
                            ("Damaged", "Damaged"),
                        ],
                        max_length=100,
                    ),
                ),
                ("returned_date", models.DateField(blank=True, null=True)),
                (
                    "asset_condition_when_returned",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Fresh", "Fresh"),
                            ("Used", "Used"),
                            ("Damaged", "Damaged"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="AssetTrackerApp.asset",
                    ),
                ),
                (
                    "asset_assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="AssetTrackerApp.employee",
                    ),
                ),
                (
                    "asset_assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
